### ISSUE TITLE
bug: error: "git clone" for "prettier" failed

### ISSUE THREAD

**Issue by ImBIOS** [t3-oss/create-t3-turbo#1226]
### Provide environment information

  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.11 GB / 15.41 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.proto/shims/node
    Yarn: 3.4.1 - ~/.proto/shims/yarn
    npm: 10.8.1 - ~/.proto/shims/npm
    bun: 1.1.30 - ~/.bun/bin/bun
    Watchman: 2024.10.14.00 - /home/linuxbrew/.linuxbrew/bin/watchman

### Describe the bug

create t3 turbo failed

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

 ➜  bunx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo t3

### Additional information

logs:

```
  main ✘!?+516 via 🥟 v1.1.30 via  v22.9.0 
 ➜  bunx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo t3
? Which package manager do you want to use? Bun 
(beta)

    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Downloading files... (This might take a momen
    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Downloading files... (This might take a momen
    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Downloading files... (This might take a momen
    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Downloading files... (This might take a momen
    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Downloading files... (This might take a momen
    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Downloading files... (This might take a momen
    Downloading files... (This might take a momen
>   Downloading files... (This might take a momen
>>  Downloading files... (This might take a momen
>>> Creating a new Turborepo with:

Application packages
 - apps/auth-proxy
 - apps/expo
 - apps/nextjs
Library packages
 - packages/api
 - packages/auth
 - packages/db
 - packages/ui
 - packages/validators
tooling
 - tooling/eslint
 - tooling/github
 - tooling/prettier
 - tooling/tailwind
 - tooling/typescript

>   Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: bun install
Resolving dependencies
error: "git clone" for "prettier" failed

error: InstallFailed cloning repository for prettier

error: "git clone" for "react" failed

error: InstallFailed cloning repository for react

error: no commit matching "" found for "react" (but repository exists)
bun install v1.1.30 (7996d06b)
    at CM (/tmp/bunx-1000-create-turbo@latest/node_modules/create-turbo/dist/cli.js:23:57)
    at /tmp/bunx-1000-create-turbo@latest/node_modules/create-turbo/dist/cli.js:23:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ph (/tmp/bunx-1000-create-turbo@latest/node_modules/create-turbo/dist/cli.js:69:2060)
    at async Command.Eg (/tmp/bunx-1000-create-turbo@latest/node_modules/create-turbo/dist/cli.js:94:7474)
    at async Command.parseAsync (/tmp/bunx-1000-create-turbo@latest/node_modules/commander/lib/command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: bun install',
  command: 'bun install',
  escapedCommand: 'bun install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'bun install v1.1.30 (7996d06b)',
  stderr: 'Resolving dependencies\n' +
    'error: "git clone" for "prettier" failed\n' +
    '\n' +
    'error: InstallFailed cloning repository for prettier\n' +
    '\n' +
    'error: "git clone" for "react" failed\n' +
    '\n' +
    'error: InstallFailed cloning repository for react\n' +
    '\n' +
    'error: no commit matching "" found for "react" (but repository exists)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by ImBIOS** [comment]
Related issue:
- https://github.com/oven-sh/bun/issues/4844

**Comment by noxify** [comment]
Could you try it with `pnpm` since it's the only supported engine, yet.

**Comment by juliusmarminge** [comment]
This repo uses pnpm. If you wanna use bun you'll need to make modifications as we're using pnpm specific features

**Comment by janwirth** [comment]
I'm having the same problem, just tried to upgrade the expo part of my project and this happened. Sad face :(
