### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by junhe** [t3-oss/create-t3-turbo#1244]
### Provide environment information

 npx envinfo --system --binaries

Need to install the following packages:
envinfo@7.14.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 169.41 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - /opt/homebrew/bin/node
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.12.3 - /opt/homebrew/bin/pnpm

### Describe the bug

npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo
? Where would you like to create your Turborepo? ./my-turborepo
? Which package manager do you want to use? npm

>>> Creating a new Turborepo with:

Application packages
 - apps/auth-proxy
 - apps/expo
 - apps/nextjs
Library packages
 - packages/api
 - packages/auth
 - packages/db
 - packages/ui
 - packages/validators
tooling
 - tooling/eslint
 - tooling/github
 - tooling/prettier
 - tooling/tailwind
 - tooling/typescript

>   Installing dependencies...
>>> Unexpected error. Please report it as a bug:
Error: Command failed with exit code 1: npm install
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "catalog:": catalog:
npm error A complete log of this run can be found in: /Users/junhe/.npm/_logs/2024-11-11T03_48_40_184Z-debug-0.log
    at CM (/Users/junhe/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:23:57)
    at /Users/junhe/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:23:8077
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ph (/Users/junhe/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:69:2060)
    at async Command.Eg (/Users/junhe/.npm/_npx/e8c68b66aeb1424f/node_modules/create-turbo/dist/cli.js:94:7474)
    at async Command.parseAsync (/Users/junhe/.npm/_npx/e8c68b66aeb1424f/node_modules/commander/lib/command.js:936:5) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  escapedCommand: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm error code EUNSUPPORTEDPROTOCOL\n' +
    'npm error Unsupported URL Type "catalog:": catalog:\n' +
    'npm error A complete log of this run can be found in: /Users/junhe/.npm/_logs/2024-11-11T03_48_40_184Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

### Link to reproduction

NA

### To reproduce

npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

Choose `npm`, instead of `pnpm`.

**Comment by juliusmarminge** [comment]
This repo is made to use pnpm which is stated in the installation guide

**Comment by junhe** [comment]
It would better to remove the `npm` option, or just say it is not supported.

**Comment by juliusmarminge** [comment]
It's not my CLI - I can't do anything about what options they choose to provide you other than telling in the installation guide to pick the supported package manager
