### ISSUE TITLE
bug: Can't create Expo Android preview build after installing `expo-updates`

### ISSUE THREAD

**Issue by matallui** [t3-oss/create-t3-turbo#362]
### Provide environment information

```
  System:
    OS: macOS 13.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 12.16 GB / 32.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/94559_1684179235576/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/94559_1684179235576/bin/npm
    Watchman: 2023.05.08.00 - /usr/local/bin/watchman
```

### Describe the bug

`eas build -p android -e preview` fails after installing `expo-updates`. Without `expo-updates` the build goes through just fine, but as soon as I install `expo-updates`, I get this error:

```
[RUN_GRADLEW] Error: @build-script-error-begin
[RUN_GRADLEW] Error loading application entry point. If your entry point is not index.js, please set ENTRY_FILE environment variable with your app entry point.
[RUN_GRADLEW] @build-script-error-end
[RUN_GRADLEW]     at /private/var/folders/87/8n6wk7dx0cl7fvmyjb5pgkjm0000gq/T/eas-build-local-nodejs/eefb9f1a-4968-499c-a323-4e1ecc6c1d91/build/node_modules/expo-updates/scripts/createManifest.js:36:11
[RUN_GRADLEW]     at Object.<anonymous> (/private/var/folders/87/8n6wk7dx0cl7fvmyjb5pgkjm0000gq/T/eas-build-local-nodejs/eefb9f1a-4968-499c-a323-4e1ecc6c1d91/build/node_modules/expo-updates/scripts/createManifest.js:99:3)
[RUN_GRADLEW]     at Module._compile (node:internal/modules/cjs/loader:1155:14)
[RUN_GRADLEW]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
[RUN_GRADLEW]     at Module.load (node:internal/modules/cjs/loader:1033:32)
[RUN_GRADLEW]     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
[RUN_GRADLEW]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
[RUN_GRADLEW]     at node:internal/main/run_main_module:22:47
```

Note: iOS builds still work fine, as well as Android development builds

### Link to reproduction

https://github.com/matallui/create-t3-turbo

### To reproduce

I created the repo above, which is a fork of this repo with a single commit on top to setup EAS build and EAS update.
However, you should be able to repro directly by:

 - cloning this repo
 - setting up eas build
 - setting up eas update
 - running `eas build -p android -e preview --local`

**Comment by GuilhermeBianeck** [comment]
Same issue, any idea guys??

**Comment by GuilhermeBianeck** [comment]
Getting worried about it

**Comment by jpelizza** [comment]
@matallui , I'm facing the same issue, although my build isn't local, I'm using expo's servers.
did you happen to find any fixes/workarounds for this?
Thanks.

**Comment by flpoliveira** [comment]
Facing the same problem here, if someone find a solution please share.

**Comment by flpoliveira** [comment]
Hey everyone! I wanted to share that I managed to successfully reintegrate expo-updates by making the following modifications:

1. I renamed the file index.tsx to App.tsx and removed the line `registerRootComponent(App)` from it.
```javascript
import { ExpoRoot } from "expo-router";
import React from "react";

// Must be exported or Fast Refresh won't update the context
export function App() {
  const ctx = require.context("./src/app");
  return <ExpoRoot context={ctx} />;
}
```
2. Then, I created a new file called index.js and added the code snippet below:

```javascript
// index.js
import { registerRootComponent } from "expo";
import { App } from './App';
export default App;
registerRootComponent(App);
```

It appears to be working fine for me now, and I hope it works for you too.

**Comment by matallui** [comment]
@flpoliveira Just tried doing that but EAS builds are failing with the following errors:
```
> Configure project :app
WARNING:The option setting 'android.enableDexingArtifactTransform.desugaring=false' is deprecated.
The current default is 'true'.
It will be removed in version 8.0 of the Android Gradle plugin.
ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.2.1)
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* Where:
[stderr] 
Build file '/home/expo/workingdir/build/apps/expo/android/app/build.gradle' line: 21
[stderr] 
* What went wrong:
[stderr] 
A problem occurred evaluating project ':app'.
[stderr] 
> path may not be null or empty string. path=''
[stderr] 
* Try:
[stderr] 
> Run with
[stderr] 
--stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
A problem occurred configuring project ':app'.
[stderr] 
> Failed to notify project evaluation listener.
[stderr] 
   > compileSdkVersion is not specified. Please add it to build.gradle
[stderr] 
   >
[stderr] 
/home/expo/workingdir/build/apps/expo/node_modules/react-native/ReactAndroid/gradle.properties (No such file or directory)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 1m 47s
10 actionable tasks: 10 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

Any ideas?

**Comment by juliusmarminge** [comment]
Should be fixed in Expo 49

**Comment by brianMxBm** [comment]
Running Expo 51 and I'm currently facing this issue.
