### ISSUE TITLE
bug: VSCode Prettier extension failed to load

### ISSUE THREAD

**Issue by martin-prochazka** [t3-oss/create-t3-turbo#485]
### Provide environment information

System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 65.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm

### Describe the bug

Error message from loading Prettier extension is shown when TS file open in VSCode.

When used `npm create t3-app@latest` it works.

Prettier version: 3.0.1

### Link to reproduction

-

### To reproduce

Clone create-t3-turbo repository, install dependencies, open in VSCode and open TS file.

### Additional information

["INFO" - 10:23:21] Extension Name: esbenp.prettier-vscode.
["INFO" - 10:23:21] Extension Version: 10.1.0.
["INFO" - 10:23:27] Attempted to load Prettier module from /Users/martinprochazka/dev/xxx-monorepo/node_modules/prettier
["ERROR" - 10:23:27] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 10:23:27] Cannot load Prettier version from package.json
Error: Cannot load Prettier version from package.json
	at t.ModuleResolver.loadPrettierVersionFromPackageJson (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:4247)
	at t.ModuleResolver.getPrettierInstance (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:5367)
	at t.default.handleActiveTextEditorChanged (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10771)
	at r.handleActiveTextEditorChangedSync [as value] (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10373)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.x (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1972)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2188)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:15496)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at c.acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:12570)
	at c.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10941)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7983)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7749)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:6830)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:5906)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4736)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:30355)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28635)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
["INFO" - 10:23:59] Attempted to load Prettier module from /Users/martinprochazka/dev/solsol-digiprojekt-monorepo/node_modules/prettier
["ERROR" - 10:23:59] Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install`
["ERROR" - 10:23:59] Cannot load Prettier version from package.json
Error: Cannot load Prettier version from package.json
	at t.ModuleResolver.loadPrettierVersionFromPackageJson (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:4247)
	at t.ModuleResolver.getPrettierInstance (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:5367)
	at t.default.handleActiveTextEditorChanged (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10771)
	at r.handleActiveTextEditorChangedSync [as value] (/Users/martinprochazka/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10373)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.x (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1972)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2188)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:15496)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at c.acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:12570)
	at c.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10941)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7983)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7749)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:6830)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:5906)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4736)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:30355)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28635)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain.emit (node:domain:489:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)

**Comment by juliusmarminge** [comment]
should be fixed in some recent refactors

**Comment by noxify** [comment]
My workaround was:

* Downgrade prettier in `<root>/package.json` to `2.8.8`
* Downgrade vsc prettier plugin to `v9.20.0`

Now there is no error in the VSC Output tab.

tbh. not sure if everything will work as expected, but it works :)
