### ISSUE TITLE
bug: Can't connect to Nextjs with base project

### ISSUE THREAD

**Issue by hanzomaster** [t3-oss/create-t3-turbo#556]
### Provide environment information

```
System:
    OS: Windows 10 10.0.23531
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 6.84 GB / 15.75 GB
Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
	pnpm: 8.6.12 - C:\Program Files\nodejs\pnpm
```

### Describe the bug

After creating a new project with `npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo` and do all the setup. I can't connect to Nextjs backend.

The error I received:
```
- error Error: Invariant: headers() expects to have requestAsyncStorage, none available.
    at Layout (./src/app/layout.tsx:42:79)
    at stringify (<anonymous>)
- warn
metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
- error TypeError: Cannot read properties of undefined (reading '')
[TypeError: Cannot read properties of undefined (reading '')]
[TypeError: Cannot read properties of undefined (reading '')]
[TypeError: Cannot read properties of null (reading 'default')]
```

### Link to reproduction

https://github.com/hanzomaster/t3-turbo

### To reproduce

```
npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

# Install dependencies
pnpm i

# Configure environment variables
# There is an `.env.example` in the root directory you can use for reference
cp .env.example .env

# Push the Drizzle schema to the database
pnpm db:push

# Run it with
pnpm --filter nextjs dev

Then connect to `localhost:3000`
```

**Comment by SergioDep** [comment]
I think it's a problem with the edge runtime, for now this has worked for me:
src/app/page.tsx
```typescript

import { Suspense } from "react";

import { AuthShowcase } from "./_components/auth-showcase";
import {
  CreatePostForm,
  PostCardSkeleton,
  PostList,
} from "./_components/posts";


// export const runtime = "edge"; <--- COMMENT THIS LINE

export default function HomePage() {
  return (
    <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        ...
    </main>
  );
}

```

**Comment by hanzomaster** [comment]
Thank you for the reply. I commented out the line and it works now. However, when access to the local nextjs route now. It through me this error about `Drizze`
```
>> query  #1 post.all  { input: undefined }
- wait compiling /api/trpc/[trpc]/route (client and server)...
- event compiled successfully in 294 ms (298 modules)
>>> tRPC Request from nextjs-react by null
>>> tRPC Error on 'post.all'  [TRPCError: fetch failed] {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError'
}
 << query  #1 post.all  {
  input: undefined,
  result: TRPCClientError: fetch failed
      at TRPCClientError.from (webpack-internal:///(ssr)/../../node_modules/@trpc/client/dist/TRPCClientError-fef6cf44.mjs:14:20)
      at eval (webpack-internal:///(ssr)/../../node_modules/@trpc/client/dist/httpBatchLink-520db465.mjs:198:105)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: { response: [Response] },
    shape: { message: 'fetch failed', code: -32603, data: [Object] },
    data: {
      code: 'INTERNAL_SERVER_ERROR',
      httpStatus: 500,
      stack: 'Error: fetch failed\n' +
        '    at context.fetch (E:\\Workspace\\Expo\\t3-turbo\\node_modules\\next\\dist\\server\\web\\sandbox\\context.js:260:38)\n' +
        '    at postJSON (webpack-internal:///(rsc)/../../node_modules/@planetscale/database/dist/index.js:137:28)\n' +
        '    at Connection.execute (webpack-internal:///(rsc)/../../node_modules/@planetscale/database/dist/index.js:89:29)\n' +
        '    at PlanetScalePreparedQuery.execute (webpack-internal:///(rsc)/../../node_modules/drizzle-orm/planetscale-serverless/index.mjs:40:39)\n' +
        '    at QueryPromise.execute (webpack-internal:///(rsc)/../../node_modules/drizzle-orm/view-3fdec7de.mjs:1465:31)\n' +
        '    at QueryPromise.then (webpack-internal:///(rsc)/../../node_modules/drizzle-orm/alias-a0c6a0a1.mjs:501:21)',
      path: 'post.all',
      zodError: null
    },
    [cause]: undefined
  },
  elapsedMs: 595
}
```
I have rechecked my database connection (I'm connecting to my MySQL local database) and everything still fine. Do you have any clue what that error might be? Thanks in advanced

**Comment by juliusmarminge** [comment]
> I'm connecting to my MySQL local database

That's probably it. The planetscale http connector cant connect to a local mysql instance
