### ISSUE TITLE
bug: A problem occurred evaluating project ':expo-modules-core'.

### ISSUE THREAD

**Issue by matadaniel** [t3-oss/create-t3-turbo#839]
### Provide environment information

```
System:
    OS: Linux 6.6 Archcraft
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 11.03 GB / 15.43 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /run/user/1000/fnm_multishells/11144_1704752906519/bin/node
    npm: 10.2.3 - /run/user/1000/fnm_multishells/11144_1704752906519/bin/npm
    pnpm: 8.14.0 - /run/user/1000/fnm_multishells/11144_1704752906519/bin/pnpm
```

### Describe the bug

Android compilation fails on a fresh install.

```
> @acme/expo@0.1.0 android /home/danielm/projects/create-t3-turbo/apps/expo
> expo run:android

✔ Created native project | gitignore skipped
› Using current versions instead of recommended expo-splash-screen@~0.20.5, react-native@0.72.6.
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using pnpm
> pnpm install
Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Config synced
› Opening emulator Pixel_3a_API_34_extension_level_7_x86_64
› Building app...
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/danielm/projects/create-t3-turbo/node_modules/expo-modules-core/android/build.gradle' line: 372

* What went wrong:
A problem occurred evaluating project ':expo-modules-core'.
> Cannot invoke method replace() on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
5 actionable tasks: 4 executed, 1 from cache
Error: /home/danielm/projects/create-t3-turbo/apps/expo/android/gradlew exited with non-zero code: 1
Error: /home/danielm/projects/create-t3-turbo/apps/expo/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/home/danielm/projects/create-t3-turbo/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at Object.spawnAsync [as default] (/home/danielm/projects/create-t3-turbo/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/home/danielm/projects/create-t3-turbo/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/home/danielm/projects/create-t3-turbo/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/home/danielm/projects/create-t3-turbo/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/home/danielm/projects/create-t3-turbo/apps/expo:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @acme/expo@0.1.0 android: `expo run:android`
Exit status 1
```

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

`git clone git@github.com:t3-oss/create-t3-turbo.git`
`cd create-t3-turbo`
`pnpm i`
`pnpm --filter expo android`

### Additional information

```
~/projects/create-t3-turbo main ?1 ❯ java -version                                                                                          18s  20.10.0
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+8)
OpenJDK 64-Bit Server VM (build 17.0.9+8, mixed mode)
```

**Comment by azizmobarak** [comment]
any solution?

**Comment by juliusmarminge** [comment]
Fxied in #795
