### ISSUE TITLE
feat: better way to validate / import env vars

### ISSUE THREAD

**Issue by LucasAlda** [t3-oss/create-t3-turbo#87]
Hello! I am moving a create-t3-app project to a turborepo based on this template, and I notice that the env checker remains in the next folder, contrary to what I would have thought since now it wouldn't be fully checking the env variables for other apps or packages. It would be great to add a new package that checks all as a dependency in the TurboRepo workflows, similar to the env folder in @acme/next.

**Comment by juliusmarminge** [comment]
Yes, if you have a good way?

**Comment by LucasAlda** [comment]
I was thinking on having the package really similar to the actual env folder, exporting the type checked env and adding a "envcheck" script that runs the zod.parse at the beginning.

I just did a quick research and I couldn't find a way to run a script before the turbo dev since that pipeline is run in parallel and doesn't wait for dependsOn. I can imagine right now to posible ways:
1. Instead of having "dev" (and build) depending on typecheck, renaming typecheck to dev and run it in parallel, but it won't be the first one and I not sure if it's going to stop the whole process having a non-zero exit on one package.
2. having the script dev: 'turbo typecheck && turbo dev'  and build: 'turbo typecheck && turbo build'

**Comment by juliusmarminge** [comment]
i dont want type check to be a prerequisite to dev - you should be able to dev even when your app has typeerrors.

I am also having second thoughts about a global env package - what if you want to run your nextjs app but dont have all the credentials for Expo? a global package here would prevent you from running any app when in reality it's only the expo app which isn't "runnable"

I added a thought in #100 about it being each app's responsibility to check their env vars. this isn't an optimal solution since you can't import the validated (and maybe transformed) environment variables in for example the `auth` package.

Curious what the best approach here is.

**Comment by LucasAlda** [comment]
> I don't want typechecking to be a prerequisite to dev - you should be able to dev even when your app has typeerrors.
I don't know why I write so many times typecheck, I was reffering to envchecking.

> I am also having second thoughts about a global env package - what if you want to run your nextjs app but dont have all the credentials for Expo? a global package here would prevent you from running any app when in reality it's only the expo app which isn't "runnable"

That's a really interesting point. It would be fantastic to have that global env package so that all of the validation process for your monorepo is still unified on one package, but separated into "env modules" that are checked or not depending on which apps or packages are starting.

I'm thinking of a function that receives an array of the env keys with the validator and a dependency array that specifies the apps/packages that use it. Maybe it's too complicated, but it would have an amazing DX. Also, I can't think of how to get the apps/packages that are going to be run.

On the other hand, the package can abandon the concept of global check while still providing the configuration to check every app for the desired environments and get them typed safely.

**Comment by adambarito** [comment]
I tried pulling the env checking into a separate monorepo package this weekend. The package ('@acme/env') defines the destructured processEnv, and exports zod schemas for all client and server env variables. It also provides the checking function. Then any other app or package can define its own env.ts file that pulls in only what it needs (by picking variables from the client and/or server zod schema). That way, the env variables and zod schema are all kept in one place.

If this seems like the right direction I'd be happy to work towards a PR.

The '@acme/env' package:
```
// packages/env/index.ts (alias '@acme/env')
import { z, ZodRawShape } from 'zod';

const processEnv = {
	// CLIENT
	NEXT_PUBLIC_APP_BASE_URL: process.env.NEXT_PUBLIC_APP_BASE_URL,
	NEXT_PUBLIC_APP_DEV_PORT: process.env.NEXT_PUBLIC_APP_DEV_PORT,
	NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY,

	// SERVER
	NODE_ENV: process.env.NODE_ENV,
	DATABASE_URL: process.env.DATABASE_URL,
	NEXTAUTH_URL: process.env.NEXTAUTH_URL,
	NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
	DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
	DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
	MAGIC_SECRET_KEY: process.env.MAGIC_SECRET_KEY,
	POSTMARK_SERVER_API_TOKEN: process.env.POSTMARK_SERVER_API_TOKEN,
};

export const clientEnvAllSchema = z.object({
	NEXT_PUBLIC_APP_BASE_URL: z.string(),
	NEXT_PUBLIC_APP_DEV_PORT:
		process.env.NODE_ENV === 'development'
			? z.string().min(1)
			: z.string().min(1).optional(),
	NEXT_PUBLIC_WEB_DEV_PORT:
		process.env.NODE_ENV === 'development'
			? z.string().min(1)
			: z.string().min(1).optional(),	
	NEXT_PUBLIC_MAGIC_PUBLISHABLE_KEY: z.string(),
});

export const serverEnvAllSchema = z.object({
	NODE_ENV: z.enum(['development', 'test', 'production']),
	// INTERNAL
	API_USER_ID: z.string(),
	NEXTAUTH_URL: z.preprocess(
		// This makes Vercel deployments not fail if you don't set NEXTAUTH_URL
		// Since NextAuth.js automatically uses the VERCEL_URL if present.
		str => process.env.VERCEL_URL ?? str,
		// VERCEL_URL doesn't include `https` so it cant be validated as a URL
		process.env.VERCEL ? z.string() : z.string().url(),
	),
	NEXTAUTH_SECRET:
		process.env.NODE_ENV === 'production'
			? z.string().min(1)
			: z.string().min(1).optional(),

	// EXTERNAL
	DATABASE_URL: z.string().url(),
	DISCORD_CLIENT_ID: z.string(),
	DISCORD_CLIENT_SECRET: z.string(),
	MAGIC_SECRET_KEY: z.string(),
	POSTMARK_SERVER_API_TOKEN: z.string(),
});

export function zEnv<TClient extends ZodRawShape, TServer extends ZodRawShape>({
	clientEnvSchema,
	serverEnvSchema,
}: {
	clientEnvSchema: z.ZodObject<TClient>;
	serverEnvSchema: z.ZodObject<TServer>;
}) {
	const isServer = typeof window === 'undefined';

	const merged = serverEnvSchema.merge(clientEnvSchema);
	const parsed = merged.safeParse(processEnv);

	if (!parsed?.success) {
		console.error(
			'❌ Invalid environment variables:\n',
			...formatErrors(parsed.error.format()),
		);
		throw new Error('Invalid environment variables');
	}

	const env = new Proxy(parsed.data, {
		get(target, prop) {
			if (typeof prop !== 'string') return undefined;
			if (!isServer && !prop.startsWith('NEXT_PUBLIC_'))
				throw new Error(
					`❌ Attempted to access server-side environment variable '${prop}' on the client`,
				);

			if (prop in target) return target[prop as keyof typeof target];

			return undefined;
		},
	});

	return env;
}

const formatErrors = (errors: z.ZodFormattedError<Map<string, string>, string>) =>
	Object.entries(errors)
		.map(([name, value]) => {
			if (value && '_errors' in value) return `${name}: ${value._errors.join(', ')}\n`;
		})
		.filter(Boolean);
```

and an example of the api pulling in what it needs:

```
// packages/api/src/env.ts
import { clientEnvAllSchema, serverEnvAllSchema, zEnv } from '@barely/env';

const serverEnvSchema = serverEnvAllSchema.pick({
	NODE_ENV: true,
	OPENAI_ORG_ID: true,
	OPENAI_API_KEY: true,
});

const clientEnvSchema = clientEnvAllSchema.pick({});

const env = zEnv({ serverEnvSchema, clientEnvSchema });

export default env;

```

**Comment by LucasAlda** [comment]
I really like this method since it allows you to have the best of both worlds: a single env file and validation on @acme/env while maintaining the granularity of only checking the variables required for the running apps. All that is required for everything to be unified and typesafe is for each individual package or app to call zEnv at the beginning.

**Comment by albertdbio** [comment]
Hey, y'all, not sure if this is the right thread, but it seems to be related.
How would we account for environment variables during the production build phase. It seems that the current env variables check in the file `env.mjs` is not able to detect `DATABASE_URL` even when explicitly set in the Vercel dashboard.
Here is the output when deploying an unmodified main branch to Vercel:
<details>
<summary>Output</summary>
[16:29:25.916] Cloning github.com/albertdbio/create-t3-turbo (Branch: main, Commit: 3cd5aa2)
[16:29:26.092] Previous build cache not available
[16:29:26.641] Cloning completed: 725.222ms
[16:29:26.642] Running "npx turbo-ignore"
[16:29:27.613] npm WARN exec The following package was not found and will be installed: turbo-ignore@0.5.0
[16:29:27.815] ≫   Using Turborepo to determine if this project is affected by the commit...
[16:29:27.816] 
[16:29:27.818] ≫   inferred "@acme/nextjs" as workspace from "package.json"
[16:29:27.819] ≫   no previous deployments found for "@acme/nextjs" on branch "main".
[16:29:27.819] 
[16:29:27.819] ✅  proceeding with deployment
[16:29:28.103] Running "vercel build"
[16:29:28.705] Vercel CLI 28.13.0
[16:29:28.861] > Automatically detected Turbo monorepo manager. Attempting to assign default settings.
[16:29:28.862] WARN! Cannot automatically assign buildCommand as it is already set via project settings or configuration overrides.
[16:29:28.862] WARN! Cannot automatically assign installCommand as it is already set via project settings or configuration overrides.
[16:29:29.142] Detected `pnpm-lock.yaml` generated by pnpm 7...
[16:29:29.152] Running "install" command: `pnpm --filter \!expo install --store=node_modules/.pnpm-store`...
[16:29:29.869] Scope: 6 of 7 workspace projects
[16:29:30.562] ../..                                    |    +1290 ++++++++++++++++++++++++++++
[16:29:30.945] ../..                                    | Progress: resolved 0, reused 0, downloaded 1, added 0
[16:29:31.238] Packages are hard linked from the content-addressable store to the virtual store.
[16:29:31.238]   Content-addressable store is at: /vercel/path0/node_modules/.pnpm-store/v3
[16:29:31.239]   Virtual store is at:             ../../node_modules/.pnpm
[16:29:31.947] ../..                                    | Progress: resolved 0, reused 0, downloaded 73, added 57
[16:29:32.961] ../..                                    | Progress: resolved 0, reused 0, downloaded 90, added 75
[16:29:33.961] ../..                                    | Progress: resolved 0, reused 0, downloaded 126, added 109
[16:29:34.971] ../..                                    | Progress: resolved 0, reused 0, downloaded 173, added 162
[16:29:35.972] ../..                                    | Progress: resolved 0, reused 0, downloaded 228, added 234
[16:29:36.976] ../..                                    | Progress: resolved 0, reused 0, downloaded 322, added 327
[16:29:37.982] ../..                                    | Progress: resolved 0, reused 0, downloaded 365, added 370
[16:29:38.993] ../..                                    | Progress: resolved 0, reused 0, downloaded 422, added 426
[16:29:39.996] ../..                                    | Progress: resolved 0, reused 0, downloaded 470, added 490
[16:29:41.001] ../..                                    | Progress: resolved 0, reused 0, downloaded 556, added 576
[16:29:42.017] ../..                                    | Progress: resolved 0, reused 0, downloaded 613, added 645
[16:29:43.031] ../..                                    | Progress: resolved 0, reused 0, downloaded 674, added 705
[16:29:44.033] ../..                                    | Progress: resolved 0, reused 0, downloaded 744, added 790
[16:29:45.036] ../..                                    | Progress: resolved 0, reused 0, downloaded 868, added 919
[16:29:46.037] ../..                                    | Progress: resolved 0, reused 0, downloaded 950, added 1016
[16:29:47.045] ../..                                    | Progress: resolved 0, reused 0, downloaded 1040, added 1109
[16:29:48.047] ../..                                    | Progress: resolved 0, reused 0, downloaded 1096, added 1172
[16:29:49.054] ../..                                    | Progress: resolved 0, reused 0, downloaded 1120, added 1218
[16:29:50.054] ../..                                    | Progress: resolved 0, reused 0, downloaded 1160, added 1270
[16:29:51.066] ../..                                    | Progress: resolved 0, reused 0, downloaded 1166, added 1281
[16:29:52.069] ../..                                    | Progress: resolved 0, reused 0, downloaded 1168, added 1283
[16:29:53.068] ../..                                    | Progress: resolved 0, reused 0, downloaded 1169, added 1285
[16:29:54.068] ../..                                    | Progress: resolved 0, reused 0, downloaded 1171, added 1287
[16:29:55.312] ../..                                    | Progress: resolved 0, reused 0, downloaded 1172, added 1287
[16:29:56.312] ../..                                    | Progress: resolved 0, reused 0, downloaded 1173, added 1289
[16:29:57.559] ../..                                    | Progress: resolved 0, reused 0, downloaded 1174, added 1289
[16:29:58.091] ../../node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
[16:29:58.092] ../../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[16:29:58.250] ../../node_modules/core-js-pure postinstall: Done
[16:29:58.571] ../..                                    | Progress: resolved 0, reused 0, downloaded 1174, added 1290, done
[16:30:00.022] ../../node_modules/@prisma/engines postinstall: Done
[16:30:00.729] ../../node_modules/prisma preinstall$ node scripts/preinstall-entry.js
[16:30:00.730] ../../node_modules/turbo postinstall$ node install.js
[16:30:00.839] ../../node_modules/prisma preinstall: Done
[16:30:00.840] ../../node_modules/prisma install$ node scripts/install-entry.js
[16:30:00.840] ../../node_modules/turbo postinstall: Done
[16:30:01.000] ../../node_modules/prisma install: Done
[16:30:01.113] ../../node_modules/@prisma/client postinstall$ node scripts/postinstall.js
[16:30:02.249] ../../node_modules/@prisma/client postinstall: prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
[16:30:02.249] ../../node_modules/@prisma/client postinstall: If you have a Prisma schema file in a custom path, you will need to run
[16:30:02.250] ../../node_modules/@prisma/client postinstall: `prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
[16:30:02.250] ../../node_modules/@prisma/client postinstall: If you do not have a Prisma schema file yet, you can ignore this message.
[16:30:02.282] ../../node_modules/@prisma/client postinstall: Done
[16:30:02.779] Done in 33.5s
[16:30:02.818] Detected Next.js version: 13.1.1
[16:30:02.884] Running "cd ../.. && npx turbo run build --filter=nextjs"
[16:30:03.491] • Packages in scope: @acme/nextjs
[16:30:03.491] • Running build in 1 packages
[16:30:03.491] • Remote caching enabled
[16:30:03.494] @acme/db:db:generate: cache bypass, force executing 49afd99840190e14
[16:30:04.151] @acme/db:db:generate: 
[16:30:04.151] @acme/db:db:generate: > @acme/db@0.1.0 db:generate /vercel/path0/packages/db
[16:30:04.151] @acme/db:db:generate: > pnpm with-env prisma generate
[16:30:04.152] @acme/db:db:generate: 
[16:30:04.836] @acme/db:db:generate: 
[16:30:04.836] @acme/db:db:generate: > @acme/db@0.1.0 with-env /vercel/path0/packages/db
[16:30:04.836] @acme/db:db:generate: > dotenv -e ../../.env -- "prisma" "generate"
[16:30:04.836] @acme/db:db:generate: 
[16:30:05.935] @acme/db:db:generate: Prisma schema loaded from prisma/schema.prisma
[16:30:06.783] @acme/db:db:generate: 
[16:30:06.783] @acme/db:db:generate: ✔ Generated Prisma Client (4.8.1 | library) to ./../../node_modules/@prisma/client in 121ms
[16:30:06.783] @acme/db:db:generate: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
[16:30:06.784] @acme/db:db:generate: ```
[16:30:06.784] @acme/db:db:generate: import { PrismaClient } from '@prisma/client'
[16:30:06.784] @acme/db:db:generate: const prisma = new PrismaClient()
[16:30:06.784] @acme/db:db:generate: ```
[16:30:07.396] @acme/nextjs:build: cache miss, executing 617b1b132d7777b4
[16:30:08.074] @acme/nextjs:build: 
[16:30:08.074] @acme/nextjs:build: > @acme/nextjs@0.1.0 build /vercel/path0/apps/nextjs
[16:30:08.075] @acme/nextjs:build: > pnpm with-env next build
[16:30:08.075] @acme/nextjs:build: 
[16:30:08.752] @acme/nextjs:build: 
[16:30:08.752] @acme/nextjs:build: > @acme/nextjs@0.1.0 with-env /vercel/path0/apps/nextjs
[16:30:08.752] @acme/nextjs:build: > dotenv -e ../../.env -- "next" "build"
[16:30:08.753] @acme/nextjs:build: 
[16:30:09.365] @acme/nextjs:build: ❌ Invalid environment variables:
[16:30:09.365] @acme/nextjs:build:  DATABASE_URL: Required
[16:30:09.365] @acme/nextjs:build:  NEXTAUTH_SECRET: Required
[16:30:09.365] @acme/nextjs:build:  DISCORD_CLIENT_ID: Required
[16:30:09.366] @acme/nextjs:build:  DISCORD_CLIENT_SECRET: Required
[16:30:09.366] @acme/nextjs:build: 
[16:30:09.366] @acme/nextjs:build: error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
[16:30:09.371] @acme/nextjs:build: 
[16:30:09.371] @acme/nextjs:build: > Build error occurred
[16:30:09.373] @acme/nextjs:build: Error: Invalid environment variables
[16:30:09.373] @acme/nextjs:build:     at file:///vercel/path0/apps/nextjs/src/env.mjs:77:9
[16:30:09.373] @acme/nextjs:build:     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[16:30:09.373] @acme/nextjs:build:     at async Promise.all (index 0)
[16:30:09.374] @acme/nextjs:build:     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
[16:30:09.374] @acme/nextjs:build:     at async file:///vercel/path0/apps/nextjs/next.config.mjs:6:38
[16:30:09.387] @acme/nextjs:build:  ELIFECYCLE  Command failed with exit code 1.
[16:30:09.399] @acme/nextjs:build:  ELIFECYCLE  Command failed with exit code 1.
[16:30:09.405] @acme/nextjs:build: ERROR: command finished with error: command (/vercel/path0/apps/nextjs) pnpm run build exited (1)
[16:30:09.406] command (/vercel/path0/apps/nextjs) pnpm run build exited (1)
[16:30:09.406]  ERROR  run failed: command  exited (1)
[16:30:09.406] 
[16:30:09.406]  Tasks:    1 successful, 2 total
[16:30:09.406] Cached:    0 cached, 2 total
[16:30:09.406]   Time:    6.014s 
[16:30:09.407] 
</details>

**Comment by adambarito** [comment]
@juliusmarminge any thoughts on this direction?

**Comment by juliusmarminge** [comment]
> @juliusmarminge any thoughts on this direction?

Looked at it briefly but will have to take a closer look this weekend. Generally think it might work?

**Comment by adambarito** [comment]
It's cleaned up how I'm handling env variables in a few different monorepo apps + packages. Another iteration I'm liking is integrating the 'baseUrl' logic into the processEnv file (instead of in a shared util that I needed to import all over the repo). 

```
const processEnv = {
	// CLIENT
	NEXT_PUBLIC_APP_BASE_URL:
		typeof window !== 'undefined'
			? '' // browser should use relative url
			: process.env.NODE_ENV === 'production'
			? `https://${process.env.VERCEL_URL}` // SSR should use vercel url
			: `http://localhost:${process.env.NEXT_PUBLIC_APP_DEV_PORT}`, // dev SSR should use localhost

	NEXT_PUBLIC_WEB_BASE_URL:
		typeof window !== 'undefined'
			? ''
			: process.env.NODE_ENV === 'production'
			? `https://${process.env.VERCEL_URL}`
			: `http://localhost:${process.env.NEXT_PUBLIC_WEB_DEV_PORT}`,

	NEXT_PUBLIC_LINK_BASE_URL:
		typeof window !== 'undefined'
			? ''
			: process.env.NODE_ENV === 'production'
			? `https://${process.env.VERCEL_URL}`
			: `http://localhost:${process.env.NEXT_PUBLIC_LINK_DEV_PORT}`,

	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,

	// SERVER
	NODE_ENV: process.env.NODE_ENV

        /// ...rest of env variables

```

Then I'm not conditionally pulling in ports and/or production urls anywhere, and the clientEnvSchema just looks like this: 

``` 
export const clientEnvAllSchema = z.object({
	NEXT_PUBLIC_APP_BASE_URL: z.string(), // for apps/app
	NEXT_PUBLIC_WEB_BASE_URL: z.string(), // for apps/web
	NEXT_PUBLIC_LINK_BASE_URL: z.string(), // for apps/link
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
});
```

**Comment by juliusmarminge** [comment]
Playing around with a bit of an alternative approach that will let you do this in each app/pkg:

![CleanShot 2023-01-29 at 00 40 27](https://user-images.githubusercontent.com/51714798/215296102-f4b862d8-e6a7-45c8-b9e3-a842245b1a99.png)

Should have something up by tomorrow

**Comment by juliusmarminge** [comment]
Checkout #135 and leave suggestions

**Comment by harry-peirse** [comment]
Hey - Thought I'd add my 2c. I really like this idea - but problem I'm having when I try to add it to my project is that I'm forced to import it as an ESM module, whereas my other packages projects don't give me the same grief. In my instance I'm wanting to create a regular Node Express app along side the Next app, and use the env variables in both. My knowledge of working around the CJS/ESM is certainly limited (and it's a complex area) so perhaps I'm missing something - but if you're aware of a way to keep this package not tied to being an ESM to my other packages that would be ideal. Thanks!

**Comment by harry-peirse** [comment]
Hey - Thought I'd add my 2c. I really like this idea - but problem I'm having when I try to add it to my project is that I'm forced to import it as an ESM module, whereas my other packages projects don't give me the same grief. In my instance I'm wanting to create a regular Node Express app along side the Next app, and use the env variables in both. My knowledge of working around the CJS/ESM is certainly limited (and it's a complex area) so perhaps I'm missing something - but if you're aware of a way to keep this package not tied to being an ESM to my other packages that would be ideal. Thanks!

**Comment by LucasAlda** [comment]
Congratulations, @juliusmarminge, on the release of t3-env!! It's incredible how you can turn a simple issue I raised 5 months ago into a great, agnostic, and simple package. You're truly on another level.

**Comment by Tobjoern** [comment]
> Congratulations, @juliusmarminge, on the release of t3-env!! It's incredible how you can turn a simple issue I raised 5 months ago into a great, agnostic, and simple package. You're truly on another level.

t3-env looks very promising! Do you know if it'll be integrated into the t3-turbo repo?
