### ISSUE TITLE
bug: Unable to run `pnpm dev` in starter pack

### ISSUE THREAD

**Issue by adamspotlite** [t3-oss/create-t3-turbo#873]
### Provide environment information

```

  System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 44.39 GB / 62.47 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 21.6.0 - ~/.local/share/nvm/v21.6.0/bin/node
    npm: 10.2.4 - ~/.local/share/nvm/v21.6.0/bin/npm
    pnpm: 8.11.0 - ~/.local/share/pnpm/pnpm
```

### Describe the bug

Upon downloading the template, I'm unable to run `pnpm dev` in `apps/expo`. I receive the following permissions error due to the `.gitignore`:

```
Starting Metro Bundler
Error: EACCES: permission denied, open '/home/learning-projects/t3-test/apps/expo/.gitignore'
    at Object.readFileSync (node:fs:456:20)
    at Object.upsertGitIgnoreContents (/home/learning-projects/t3-test/node_modules/@expo/cli/src/utils/mergeGitIgnorePaths.ts:121:30)
    at Object.startTypescriptTypeGenerationAsync (/home/learning-projects/t3-test/node_modules/@expo/cli/src/start/server/type-generation/startTypescriptTypeGeneration.ts:51:85)
   ```

### Link to reproduction

https://github.com/t3-oss/create-t3-turbo

### To reproduce

```
npx create-turbo@latest -e https://github.com/t3-oss/create-t3-turbo

cd repo_name

pnpm i

cd apps/expo

pnpm dev
```

**Comment by parz1** [comment]
same issue here and don want to execute with `sudo`

**Comment by AMayer1997** [comment]
Hi, I had the same issue. It looks like the `.gitignore` file gets generated without any rwx permissions. I fixed the issue by deleting the file and creating an empty `/apps/expo.gitignore` file. The file should get updated automatically once you run `pnpm dev` again.

**Comment by burakkgunduzz** [comment]
> Hi, I had the same issue. It looks like the `.gitignore` file gets generated without any rwx permissions. I fixed the issue by deleting the file and creating an empty `/apps/expo/.gitignore` file. The file should get updated automatically once you run `pnpm dev` again.

your solution worked for .gitignore but now I get the same error for router.d.ts 
```Starting Metro Bundler
Using src/app as the root directory for Expo Router.
Error: EACCES: permission denied, open '/Users/burakgunduz/Documents/development/personal/testapp/apps/expo/.expo/types/router.d.ts'
/Users/burakgunduz/Documents/development/personal/testapp/apps/expo:```

**Comment by juliusmarminge** [comment]
Can you please verify that this doesnt happen on a normal expo app? I dont see why this would be a cause of t3 turbo so this issue should likely be opened upstream?

**Comment by AMayer1997** [comment]
It works for me with a normal expo app. An intact `.gitignore` file gets generated with the cli: `npx create-expo-app my-app`.

btw thanks for your open source contributions

**Comment by IanWorley** [comment]
I want to report I have the same issue and I fix the issue by adding file permissions to the .gitignore and running `pnpm run dev`

**Comment by Evanion** [comment]
I can confirm that this is not a T3 issue, I get the same in an NX monorepo

**Comment by adamspotlite** [comment]
Does anyone know where to put this then? I feel like the proper steps are:

1) Close this issue
2) Make a note somewhere that there is a solution to the solution (namely, running `chmod 644 apps/expo/.gitignore`)
3) Add a new issue in one of the `expo-cli` repos

**Comment by psycho-baller** [comment]
Is there anything wrong with just manually adding a `.gitignore` file to the expo directory as @AMayer1997 mentioned [here](https://github.com/t3-oss/create-t3-turbo/issues/873#issuecomment-1923598382)

> Hi, I had the same issue. It looks like the `.gitignore` file gets generated without any rwx permissions. I fixed the issue by deleting the file and creating an empty `/apps/expo/.gitignore` file. The file should get updated automatically once you run `pnpm dev` again.

**Comment by adamspotlite** [comment]
@psycho-baller not that I can tell - I think that's likely what most folks end up doing (myself included), without any downstream implications.

**Comment by adamspotlite** [comment]
> Does anyone know where to put this then? I feel like the proper steps are:
> 
> 1. Close this issue
> 2. Make a note somewhere that there is a solution to the solution (namely, running `chmod 644 apps/expo/.gitignore`)
> 3. Add a new issue in one of the `expo-cli` repos

@juliusmarminge should i go through with this? I don't think this needs to be an active issue, but I feel it should be documented for future reference.

**Comment by juliusmarminge** [comment]
I opened an issue right after expo started generating gitignore that got converted to discussion (see https://github.com/expo/router/discussions/846)

**Comment by dBianchii** [comment]
Happening to me as well

**Comment by swebreza** [comment]
OS : Windows 11

go to apps/expo/ and run following command. I will suggest 2nd one because it worked for me. 

1) `icacls .gitignore /grant "%username%":F`
or
2) `attrib -r .gitignore`

**Comment by recallwei** [comment]
+1

**Comment by CarlosZiegler** [comment]
Tested right now and have same issue :)

**Comment by CarlosZiegler** [comment]
Then cli create new again

**Comment by swebreza** [comment]
try this
`attrib -r .gitignore`

**Comment by CarlosZiegler** [comment]
Works if use `sudo`, but this is not a solution :(

**Comment by pabrcno** [comment]
If you are using windows, change Properties > attributes > Read-only on /apps/expo/.gitignore. 
![image](https://github.com/user-attachments/assets/810483e5-c066-44f6-ae4c-d8a372475648)

**Comment by ancill** [comment]
Linux user here.
Solved by 
```cd apps/expo```
```chmod 777 .gitignore```

**Comment by bdtren** [comment]
In my case, the `.gitignore` also cannot open in visual studio code.
So I did this and the issue gone:
- Remove the not openable `.gitignore`
- Create a new empty `.gitignore` file
- Run `npx expo start`
